--liquibase formatted sql
--changeset "ivkam":3

CREATE TABLE IF NOT EXISTS public.default_subcategory
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    def_sub_type integer NOT NULL,
    def_sub_color character varying(255) COLLATE pg_catalog."default" NOT NULL,
    def_sub_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    def_sub_parent_cat_id bigint,
    CONSTRAINT default_subcategory_pkey PRIMARY KEY (id),
    CONSTRAINT UNIQUE_CONSTRAIN_SUB_CAT_NAME UNIQUE (def_sub_name),
    CONSTRAINT FOREIGN_KEY_PARENT_CATEGORY FOREIGN KEY (def_sub_parent_cat_id)
    REFERENCES public.default_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
)