--liquibase formatted sql
--changeset "ivkam":3

CREATE TABLE IF NOT EXISTS public.default_category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    def_cat_type integer NOT NULL,
    def_cat_color character varying(255) COLLATE pg_catalog."default" NOT NULL,
    def_cat_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT default_category_pkey PRIMARY KEY (id),
    CONSTRAINT UNIQUE_CONSTRAIN_CAT_NAME UNIQUE (def_cat_name)
)