--liquibase formatted sql
--changeset "ivkam":3

CREATE TABLE IF NOT EXISTS public.categories
(
    cat_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cat_is_default boolean NOT NULL,
    cat_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (cat_id),
    CONSTRAINT CAT_NAME UNIQUE (cat_name)
)