version: '3.5'

services:
  postgresql:
    container_name: postgres-db
    image: postgres:13.7
    restart: unless-stopped
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres/13.7/data:/var/lib/postgresql/data
    - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    env_file:
    - postgres.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
