name: Checkstyle on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/try-to-laugh/sandboxOpenApiSchema" }]'
          servers: '[{ "id": "github", "username": "AlexPravda1", "password": "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" }]'
          output_file: .m2/settings.xml

      - name: Checkstyle with Maven
        run: mvn --settings ~/.m2/settings.xml -f finance_manager/pom.xml -B verify checkstyle:checkstyle
